# Reference compose file version 3
version: '3.9'
services:
  # Service name is react-app
  react-app:
    # build from Dockerfile
    build: .
    # expose 3000 as hosting port & 3000 in container port
    ports:
      - "3000:3000"
    volumes:
      - .:/app

