version: '3.9'
services:
  mysql1:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: db2
    volumes:
      - ./dbfiles:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
  node1:
    build: 
      context: .
    container_name: nodejs1
    # hostname: nodejs-container
    ports:
    - "80:8080"
    volumes:
    - .:/usr/src/app
    depends_on:
      mysql1:
        condition: service_started
    stdin_open: true
    tty: true



# version: '3.9'

# services:
#   couchdb1:
#     image: couchdb:3.2.0
#     container_name: cdb1
#     ports:
#       - "5984:5984"
#     volumes:
#       - ./db:/opt/couchdb/data
#     environment:
#       COUCHDB_USER: admin
#       COUCHDB_PASSWORD: admin

  # # React service
  # react_app:
  #   build:
  #     context: ./client
  #   volumes:
  #     - ./client:/usr/src/app
  #   ports:
  #     - "80:3000"
  #   depends_on:
  #     - node_app